<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2K3DEDH" failures="3" tests="18" name="com.lp.qa.testcases.PatientResponsiblityTests" time="653.250" errors="2" timestamp="2021-03-01T16:34:04 IST" skipped="0">
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC19_PR_verifyPRWithoutInsTransactionUserLoginID" time="32.652"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! User Login ID found in Transaction Report grid as : heartlandemail  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC03_PR_VerifyCollectCardPageforNewPatient" time="42.669">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;css selector&quot;,&quot;selector&quot;:&quot;#CardNumber&quot;}
  (Session info: chrome=88.0.4324.190)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-2K3DEDH&#039;, ip: &#039;10.100.10.144&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;14.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.190, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\sys\AppData\Local\...}, goog:chromeOptions: {debuggerAddress: localhost:63478}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 077b26b00097d3bdced2df6f1f41e140
*** Element info: {Using=id, value=CardNumber}" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#CardNumber"}
  (Session info: chrome=88.0.4324.190)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-2K3DEDH', ip: '10.100.10.144', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.190, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\sys\AppData\Local\...}, goog:chromeOptions: {debuggerAddress: localhost:63478}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 077b26b00097d3bdced2df6f1f41e140
*** Element info: {Using=id, value=CardNumber}
at jdk.internal.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
at org.openqa.selenium.By$ById.findElement(By.java:188)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at com.lp.qa.pages.CollectCardPage.collectCardPayment(CollectCardPage.java:60)
at com.lp.qa.testcases.PatientResponsiblityTests.TC03_PR_VerifyCollectCardPageforNewPatient(PatientResponsiblityTests.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC03_PR_VerifyCollectCardPageforNewPatient -->
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Communication Report Menu! Communication Report has been ran successfully! Payment URL has been opened in browser,URL as followshttps://demo.liquid-payments.com/collectcard/?reference=48482;  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC10_PR_verifyRefundVoidFunctForPatRespTransaction" time="39.523"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Refund Void Transaction has been completed!,RefundVoid Transaction ID is :278115  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC01_PR_VerifyPatRespWithInsurancePayment" time="34.293"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! PatientResponsiblity payment option has been selected successfully! PatientResponsiblity payment with Insurance data entered successfully!  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC17_PR_verifyPRWithoutInsTransactionAmount" time="32.627">
    <failure message="expected [5.23] but found [5.23]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [5.23] but found [5.23]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.lp.qa.testcases.PatientResponsiblityTests.TC17_PR_verifyPRWithoutInsTransactionAmount(PatientResponsiblityTests.java:265)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC17_PR_verifyPRWithoutInsTransactionAmount -->
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Transaction Amount found in Report grid as : $5.23  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC09_PR_verifyRefundFuctionalityForPatientResponTransaction" time="41.487"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Refund action icon click Success! Refund Transaction has been completed!,Refund Transaction ID is :278114  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC08_PR_verifyPRWithInsLoginIDInCommReport" time="33.549"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! User Login ID found in Transaction Report grid as : heartlandemail  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC02_PR_VerifyAmountInCommReport" time="39.785">
    <failure message="expected [3.12] but found [3.12]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [3.12] but found [3.12]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.lp.qa.testcases.PatientResponsiblityTests.TC02_PR_VerifyAmountInCommReport(PatientResponsiblityTests.java:99)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC02_PR_VerifyAmountInCommReport -->
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Communication Report Menu! Communication Report has been ran successfully! Payment amount found in Communication Report as :$3.12  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC07_PR_verifyPRWithInsPatientNameInCommReport" time="32.092"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Patient Name found in Report grid as : John Smith  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC06_PR_verifyPRWithInsAmountInCommReport" time="30.696">
    <failure message="expected [3.12] but found [3.12]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [3.12] but found [3.12]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.lp.qa.testcases.PatientResponsiblityTests.TC06_PR_verifyPRWithInsAmountInCommReport(PatientResponsiblityTests.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC06_PR_verifyPRWithInsAmountInCommReport -->
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Transaction Amount found in Report grid as : $3.12  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC13_PR_VerifyPatientResponsibilityWithoutInsurance" time="41.420">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;css selector&quot;,&quot;selector&quot;:&quot;#CardNumber&quot;}
  (Session info: chrome=88.0.4324.190)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DESKTOP-2K3DEDH&#039;, ip: &#039;10.100.10.144&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;14.0.1&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.190, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\sys\AppData\Local\...}, goog:chromeOptions: {debuggerAddress: localhost:65267}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 02834392c07f52b396f016cf2b106084
*** Element info: {Using=id, value=CardNumber}" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#CardNumber"}
  (Session info: chrome=88.0.4324.190)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-2K3DEDH', ip: '10.100.10.144', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.190, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\sys\AppData\Local\...}, goog:chromeOptions: {debuggerAddress: localhost:65267}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 02834392c07f52b396f016cf2b106084
*** Element info: {Using=id, value=CardNumber}
at jdk.internal.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
at org.openqa.selenium.By$ById.findElement(By.java:188)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at com.lp.qa.pages.CollectCardPage.collectCardPayment(CollectCardPage.java:60)
at com.lp.qa.testcases.PatientResponsiblityTests.TC13_PR_VerifyPatientResponsibilityWithoutInsurance(PatientResponsiblityTests.java:237)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC13_PR_VerifyPatientResponsibilityWithoutInsurance -->
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Communication Report Menu! Communication Report has been ran successfully! Payment URL has been opened in browser,URL as followshttps://demo.liquid-payments.com/collectcard/?reference=48482;  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC18_PR_verifyPRWithoutInsTransactionPatientName" time="30.665"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Patient Name found in Report grid as : John Smith  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC20_PR_verifyPRWithoutInsTransactionRefund" time="38.470"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Refund action icon click Success! Refund Transaction has been completed!,Refund Transaction ID is :278118  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC21_PR_verifyPRWithoutInsTransactionRefundVoid" time="37.607"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Refund Void Transaction has been completed!,RefundVoid Transaction ID is :278119  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC22_PR_verifyPRwithoutInsTransactionAuthVoid" time="39.801"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Authorize Void Transaction has been completed!,Authorize Void Transaction ID is :278120  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC12_PR_PatientRespFormWithoutInsurance" time="33.843"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! PatientResponsiblity payment option has been selected successfully! PatientResponsiblity without insurance payment data has been entered successfully! PatientResponsiblity without insurance payment data has been entered successfully!  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC11_PR_verifyVoidfunctforPatientRespTransaction" time="42.213"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Authorize Void Transaction has been completed!,Authorize Void Transaction ID is :278116  </system-out>
  <testcase classname="com.lp.qa.testcases.PatientResponsiblityTests" name="TC15_PR_verifyPRWithoutInsTransactionStatus" time="29.858"/>
  <system-out>
Chrome browser launched Successfully! Application has been launched successfully! User logged in to the Application! Navigated to Transaction Report menu! Transaction Report has been ran Successfully! Transaction Status has found in Transaction Report grid with Status as : Approved  </system-out>
</testsuite> <!-- com.lp.qa.testcases.PatientResponsiblityTests -->
